name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  MIX_ENV: test
  ARCA_CONFIG_CONFIG_PATH: .arca_config
  ARCA_CONFIG_CONFIG_FILE: config.json

jobs:
  test:
    name: Test on OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - otp: '27.0'
            elixir: '1.18.0'
          - otp: '28.0'
            elixir: '1.18.4'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
        elixir-version: ${{ matrix.elixir }}
    
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-
          ${{ runner.os }}-mix-
    
    - name: Install hex and rebar
      run: |
        mix local.hex --force
        mix local.rebar --force
    
    - name: Install dependencies
      run: mix deps.get
    
    - name: Compile dependencies
      run: mix deps.compile
    
    - name: Compile application
      run: mix compile --warnings-as-errors
    
    - name: Run tests
      run: mix test
      
    - name: Check formatting
      run: mix format --check-formatted
      
    # Run coverage only on latest Elixir/OTP combination
    - name: Run tests with coverage
      if: matrix.elixir == '1.18.4' && matrix.otp == '28.0'
      run: mix test --cover || true